name: Deploy to Netlify
on:
  push:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build dist folder
      run: |
        mkdir -p build
        cp -r css js fonts img screenshots font-awesome favicon.png index.html build/
        
    - name: Upload to Netlify
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=build
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
